-- preprint-link.lua
--
-- Companion filter for nature-no-et-al.csl's "preprint" macro.
--
-- CSL/citeproc has no way to give a hyperlink different display text
-- than the URL it points to, so the style instead emits a plain-text
-- marker: {{PREPRINT:<url>}}. This filter finds that marker anywhere
-- in the document (in practice: inside the bibliography, generated by
-- pandoc's --citeproc pass) and replaces it with a line break followed
-- by a real hyperlink whose visible text is "[Preprint]", so the link
-- appears on its own line below the rest of the citation.
--
-- Usage (the filter must run AFTER citeproc, so list it after
-- --citeproc on the command line, or after 'citeproc' in a Quarto
-- `filters:` list):
--
--   pandoc paper.md --citeproc --csl=nature-no-et-al.csl \
--     --lua-filter=preprint-link.lua -o paper.html
--
-- Quarto:
--   filters:
--     - citeproc
--     - preprint-link.lua

local function split_marker(text)
  -- The marker can have punctuation glued onto either side, with no
  -- space, since the CSL style emits it right after the citation's
  -- closing "." with no delimiter (so the line break lands right
  -- before the link rather than after a trailing space). Search for
  -- the marker anywhere in the token rather than anchoring the match.
  local s, e, url = text:find("{{PREPRINT:(.-)}}")
  if not s then
    return nil
  end
  local leading = text:sub(1, s - 1)
  local trailing = text:sub(e + 1)
  return url, leading, trailing
end

function Str(el)
  local url, leading, trailing = split_marker(el.text)
  if not url then
    return nil
  end
  local link = pandoc.Link({ pandoc.Str("[Preprint]") }, url)
  local out = {}
  if leading ~= "" then
    table.insert(out, pandoc.Str(leading))
  end
  table.insert(out, pandoc.LineBreak())
  table.insert(out, link)
  if trailing ~= "" then
    table.insert(out, pandoc.Str(trailing))
  end
  return out
end
